<a href="https://colab.research.google.com/github/ucfilho/RTC_case_02_optimization/blob/master/RTC_DE_case_02_aproach_D_abril_11_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from scipy.optimize import differential_evolution
import numpy as np
import matplotlib.pyplot as plt

In [2]:
!git clone https://github.com/ucfilho/raianars_RTC_optimization #clonar do Github
%cd raianars_RTC_optimization
import de_bounds_matriz

fatal: destination path 'raianars_RTC_optimization' already exists and is not an empty directory.
/content/raianars_RTC_optimization


In [0]:
def SharkBuildMatriz(x):
  # Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha=SharkBuildMatriz(x)
  # add one position in three variables (Ind_J,Ind_I,deltaT)
  # Alfa and Split (split choose the moment and alpha the fraction)
  # Split=which stream
  # Alfa=fraction 
  
  global Trocas
  NPAR=1
  #cols=len(tempInicial)
  size=int(3*Trocas+3) # number 3 represent split, alfa and WhenSplit
  # add one exchange
  x=np.array(x).reshape(1,size)
  # print('x=');print(x)
  Ind_I=np.zeros((NPAR,Trocas)).astype(np.int64)
  Ind_J=np.zeros((NPAR,Trocas)).astype(np.int64)
  
  Tout=np.zeros((NPAR,Trocas))
  deltaT=np.zeros((NPAR,Trocas))
  for i in range(NPAR):
    Alpha=x[i,size-3]
    Split=round(x[i,size-2]).astype(np.int64)
    WhenSplit=round(x[i,size-1]).astype(np.int64)
    for j in range(Trocas):
      #print('[i,j]=%d %d'%(i,j))
      Ind_I[i,j]=round(x[i,j])
      Ind_J[i,j]=round(x[i,j+Trocas])
      deltaT[i,j]=x[i,j+2*Trocas] 
    '''
    for jj in range(cols):
      Tin[i,jj]=tempInicial[jj]
      Tout[i,jj]=tempAtual[jj]
    '''

  return Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha
  #Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha=SharkBuildMatriz(x)

In [4]:
'''
def FixSplit(x):
  
  global Trocas, mCp,  tempInicial, tempAtual, tempAlvo 
  Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha=SharkBuildMatriz(x)
  if(tempInicial[Split]>tempAlvo[Split]):
'''

'\ndef FixSplit(x):\n  \n  global Trocas, mCp,  tempInicial, tempAtual, tempAlvo \n  Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha=SharkBuildMatriz(x)\n  if(tempInicial[Split]>tempAlvo[Split]):\n'

In [0]:
def Temperatura(x):
  global Trocas, mCp,tempInicial,tempAlvo
  
  print(tempInicial)
  NPAR=1
  Tin=np.zeros(Trocas)
  mCpin=np.zeros(Trocas)
  erro=np.zeros((NPAR)) # valor erro se torna erro=1 quando ha algum erro e vai penalizar

  Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha=SharkBuildMatriz(x)
  if(WhenSplit==Trocas-1):
    Ind_1st=WhenSplit-1
    Ind_2nd=WhenSplit
  else:
    Ind_1st=WhenSplit
    Ind_2nd=WhenSplit+1
  
  if(tempInicial[Split]>tempAlvo[Split]): # hot stream is spliting
    Ind_I[0,Ind_1st]=Split # two streams are correct by split information
    Ind_I[0,Ind_2nd]=Split # two streams are correct by split information
  else: # cold stream is spliting
    Ind_J[0,Ind_1st]=Split # two streams are correct by split information
    Ind_J[0,Ind_2nd]=Split # two streams are correct by split information

  for kk in range(Trocas-1):
    Tin[kk]=tempInicial[kk]
    mCpin[kk]=mCp[kk]
  Tin[Trocas-1]=tempInicial[Trocas-2]
  mCpin[Trocas-1]=mCpin[Trocas-2]

  Aux=np.copy(Tin)
  Aux_cp=np.copy(mCpin)      
  for k in range(Split,Trocas-1):
    Tin[k+1]=Aux[k]
    mCpin[k+1]=Aux_cp[k]

  mCpout=np.copy(mCpin)
  if(Split==Trocas-1):
    mCpout[Split-1]= Alpha*mCpout[Split-1]
    mCpout[Split]= (1-Alpha)*mCpout[Split-1]
  else:
    mCpout[Split]=Alpha*mCpout[Split]
    mCpout[Split+1]= (1-Alpha)*mCpout[Split+1]
  
  

  '''
  for ki in range(NPAR):
    for kj in range(Trocas):
      #Tin=np.copy(Tout)
      k=kj
      i=Ind_I[ki,kj]
      j=Ind_J[ki,kj]
      
      tempSaidaQ=Tout[ki,i]+deltaT[ki,kj]
      tempSaidaF=-mCp[kj]*deltaT[ki,kj]/(mCp[j])+Tout[ki,j]
      flag=0 # flag : indica que nao entra no teste logico
      # usei flag no lugar q ifs pq a identacao ficou melhor assim
      if(Tout[ki,i] > Tout[ki,j]): #Tquente maior Tfria: vaores atuais
        if(tempSaidaQ > tempSaidaF): #Tquente maior Tfria: saidas
          flag=1
      if(flag>0):
        Tout[ki,i]=tempSaidaQ
        Tout[ki,j]=tempSaidaF
      else:
        erro[ki]=1
  '''
  # return Tout,erro
  # return Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha # fake return until test
  # return Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha,Tin # fake return until test
  # return Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha,Tin, mCpin # fake return until test
  return Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha,Tin, mCpin, mCpout # fake return until test

In [0]:
def Area(x):

  global mCp,tempAlvo,tempInicial,Trocas,U
  
  NPAR=1
  
  Area=[]

  Ind_I,Ind_J,deltaT,Tin, Tout=buildMatriz(x) 
  Tatual=np.copy(np.array(tempInicial))

  rows=Trocas 
  cols=len(mCp)

  Area_Particula=[]

  for k in range(Trocas):

    i=Ind_I[0,k]
    j=Ind_J[0,k]
    tempSaidaQ=Tatual[i]+deltaT[0,k]
    tempSaidaF=-deltaT[0,k]*mCp[i]/(mCp[j])+Tatual[j]

    Told_i=Tatual[i]
    Told_j=Tatual[j]

    Tatual[i]=np.copy(tempSaidaQ)
    Tatual[j]=np.copy(tempSaidaF)
    deltaT1=Tatual[i]-tempSaidaF
    deltaT2=tempSaidaQ-Tatual[j]
    try:
      A=(deltaT1-deltaT2)
      B=np.log((deltaT1/deltaT2))
      deltaTMediaLog=A/B
    except:
      deltaTMediaLog=1e99
  
    if(deltaTMediaLog==1e99):
      AreaCalc=1e99
    else:
      AreaCalc=abs(deltaT[0,k]*mCp[i]/(U*deltaTMediaLog))

    if(Told_i==Tatual[i]):
      AreaCalc=0

    if(Told_j==Tatual[j]):
      AreaCalc=0

      Area_Particula.append(AreaCalc)
      
  Area.append(Area_Particula)

  return Area

In [0]:
#def mCpSplit(mCp,Alpha,Split)

In [0]:
def Utilidades(tempAlvo,Tout,mCp):

  cols=len(mCp)
  NPAR=1
  '''
  caso I cita TUQin=553 e TQout=552, TUFin=303 TUFout=353
  '''
  TUQin=553
  TUQout=552
  TUFin=303 
  TUFout=353
  
  Areas=[]
  cargaUQtodas=[]
  cargaUFtodas=[]

  for ki in range(NPAR):
    areaTrocador=[]
    cargaUQ=0
    cargaUF=0
    for j in range(cols):
      delta=tempAlvo[j]-Tout[ki,j]
      if(delta>0):#usa UQ
        cargaUQ=cargaUQ+mCp[j]*delta
        deltaT1=(TUQin-tempAlvo[j])
        deltaT2=(TUQout-Tout[ki,j])

        try:
          A=deltaT1-deltaT2
          B=np.log(deltaT1/deltaT2)
          deltaTMediaLog=A/B
        except:
          deltaTMediaLog=1e99

        if(deltaTMediaLog==1e99):
          areaTrocador.append(1e99)
        else:
          areaTrocador.append((abs(mCp[j]*(delta)/(U*deltaTMediaLog))))

      elif(delta==0):#nao usa UF e UQ
        deltaTMediaLog=0
        areaTrocador.append(0) 

      else:#usa UF
        deltaT1=(Tout[ki,j]-TUFout)
        deltaT2=(tempAlvo[j]-TUFin)     
        cargaUF=cargaUF+mCp[j]*(-delta)

        #UF -> água resfriada -> entra a 303K e sai a 353K
        try:
          A=deltaT1-deltaT2
          B=np.log(deltaT1/deltaT2)
          deltaTMediaLog=A/B
        except:
          deltaTMediaLog=1e99
        
        if(deltaTMediaLog==1e99):
          areaTrocador.append(1e99)
        else:
          areaTrocador.append((abs(mCp[j]*(-delta)/(U*deltaTMediaLog))))

    cargaUQtodas.append(cargaUQ)
    cargaUFtodas.append(cargaUF)

    Areas.append(areaTrocador)

  return Areas, cargaUQtodas,cargaUFtodas 


In [0]:
def CustoProcesso(Area,Utilidades,cargaUFtodas,cargaUQtodas):
  global coefCustoUQ,coefCustoUF
  
  NPAR=1

  cost=np.zeros((NPAR))
  for i in range(NPAR):
    cargaUQ=cargaUQtodas[i]
    cargaUF=cargaUFtodas[i]
    areaTrocadores=Area[i]
    areaUtilidades=Utilidades[i]
    costTrocadores=0
    for it in areaTrocadores:
      for wii in areaUtilidades:
        if(it<1e99):
          if(wii<1e99):
            costTrocadores=costTrocadores+300*(it**0.5+wii**0.5)
          else:
            costTrocadores=1e99
            break
    costUQ=coefCustoUQ*cargaUQ
    costUF=coefCustoUF*cargaUF
    
    if(costTrocadores==1e99):
      cost[i]=1e99
    else:
      cost[i]=costUQ+costUF+costTrocadores
      
  return cost

In [0]:
def Numb(x):
  global mCp,tempAlvo,tempInicial,Trocas

  Ind_I,Ind_J,deltaT,Tin, Tout=buildMatriz(x) # transforma x em matriz logica e troca
  Tatual=np.copy(np.array(tempInicial))

  rows=Trocas 
  cols=len(mCp)
  Ttrocas=np.zeros((rows+4,cols))# feito em quaduplicata so para melhorar o visual
  for i in range(2):
    for j in range(cols):
      Ttrocas[i,j]=np.copy(Tatual[j])
  cont=1

  for k in range(Trocas):
    cont=cont+1
    i=Ind_I[0,k]
    j=Ind_J[0,k]
    tempSaidaQ=Tatual[i]+deltaT[0,k]
    tempSaidaF=-deltaT[0,k]*mCp[i]/(mCp[j])+Tatual[j]
    Tatual[i]=np.copy(tempSaidaQ)
    Tatual[j]=np.copy(tempSaidaF)

    for jj in range(cols):
      Ttrocas[cont,jj]=Tatual[jj]  

  for jj in range(cols): # feito em duplicata so para melhorar o visual
    Ttrocas[cont+1,jj]=tempAlvo[jj]
    Ttrocas[cont+2,jj]=tempAlvo[jj]

  return Ttrocas


In [0]:
#FUN calcula o TAC para um determinado arranjo
#  cada calculo é feito em uma funcao a parte Fun usa todas funcoes 

def FUN(x):

  global mCp,tempAtual,tempAlvo,tempInicial,U,coefCustoUQ,coefCustoUF
  
  NPAR=1
  '''
  funr=np.zeros((NPAR))
  cols=len(mCp)
  Ind_I,Ind_J,deltaT, Tin, Tout=buildMatriz(x) # transforma x em matriz logica e troca
  Tout, Erro=Temperatura(x)
  areaTrocadores =Area(x)
  areaUtilidade, cargaUQ,cargaUF = Utilidades(tempAlvo,Tout,mCp)
  cost=CustoProcesso(areaTrocadores,areaUtilidade,cargaUF,cargaUQ)
  funr=cost

  for k in range(NPAR):
    if(Erro[k]>0):
      funr[k]=1e99
  funr = np.where(np.isnan(cost), 1e99, cost)
  '''
  funr=1e99 # fake line (temporary)
  return funr 

In [12]:
#********************PROGRAMA PRINCIPAL*************************

Trocas=5
mCp=[4,2,1.5,3] #[kW/K]
tempInicial=[453.0,393.0,523.0,533.0] #[K]
tempAtual=np.copy(tempInicial) 
tempAlvo=[513.0,508.0,403.0,433.0] #[K]
U=0.2 #[kW/(m2.K)]
coefCustoUQ=110 #[$/(kW.ano)]
coefCustoUF=12.2 #[$/(kW.ano)]





#MAX=np.array([3,3,3,3,1,1,1,1,0,0,0,0])
#MIN=np.array([2,2,2,2,0,0,0,0,-100,-100,-100,-100])
MAX=np.array([3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,1,3,4]) # ,1,3,4]) Alpha,Split,WhenSplit
# the last position in MAX and MIN vector represent which moment the split 
#    occur not which stream (split represent which stream)
MIN=np.array([0,0,0,0,0,0,0,0,0,0,-100,-100,-100,-100,-100,0,0,0])

NPAR=1
cols=int(3*Trocas+3)
x=np.zeros((NPAR,cols))

for i in range(NPAR):
  for j in range(cols):
    r=np.random.random()
    x[i,j]=r*(MAX[j]-MIN[j])+MIN[j]




'''
bounds=[]
for k in range(len(MAX)):
  bounds.append((MIN[k],MAX[k]))


# print(bounds)

'''

'\nbounds=[]\nfor k in range(len(MAX)):\n  bounds.append((MIN[k],MAX[k]))\n\n\n# print(bounds)\n\n'

In [13]:



Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha=SharkBuildMatriz(x)
print(Ind_I)
print(Ind_J)
print(deltaT)
print(Split)
print(Alpha)
print(WhenSplit)

print('=====================')
#Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha=Temperatura(x) # fake Temperatura(x)
#Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha, Tin=Temperatura(x) # fake Temperatura(x)
#Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha,Tin, mCpin=Temperatura(x) # fake Temperatura(x)
Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha,Tin, mCpin,mCpout=Temperatura(x) # fake Temperatura(x)
print(Ind_I)
print(Ind_J)
print(deltaT)
print('Split=',Split)
print(Alpha)
print('WhenSplit=',WhenSplit)
print(Tin) # fake just to test
print(mCpin) # fake just to test
print(mCpout) # fake just to test

[[1 3 1 0 2]]
[[2 2 3 2 1]]
[[-79.10588056 -36.83063494 -47.14295654 -59.01711812  -8.94746041]]
0
0.5475044356112073
1
[453.0, 393.0, 523.0, 533.0]
[[1 3 1 0 2]]
[[2 0 0 2 1]]
[[-79.10588056 -36.83063494 -47.14295654 -59.01711812  -8.94746041]]
Split= 0
0.5475044356112073
WhenSplit= 1
[453. 453. 393. 523. 533.]
[4.  4.  2.  1.5 3. ]
[2.19001774 1.80998226 2.         1.5        3.        ]


In [14]:
'''
fobj=FUN
mut=0.5
crossp=0.5
NPAR=100
its=200
cols=12
x=np.zeros((NPAR,cols))
for i in range(NPAR):
  for j in range(cols):
    r=np.random.random()
    x[i,j]=r*(MAX[j]-MIN[j])+MIN[j]

x,BEST,FOBEST,XY,BEST_XY=de_bounds_matriz.de(bounds, mut, crossp, 
                                             NPAR, its,fobj,x)
'''

'\nfobj=FUN\nmut=0.5\ncrossp=0.5\nNPAR=100\nits=200\ncols=12\nx=np.zeros((NPAR,cols))\nfor i in range(NPAR):\n  for j in range(cols):\n    r=np.random.random()\n    x[i,j]=r*(MAX[j]-MIN[j])+MIN[j]\n\nx,BEST,FOBEST,XY,BEST_XY=de_bounds_matriz.de(bounds, mut, crossp, \n                                             NPAR, its,fobj,x)\n'

In [0]:
#print('FOBEST=');print(FOBEST)

In [0]:
#print(BEST)

In [17]:
'''
Busca=Numb(BEST)
print(pd.DataFrame(Busca))
df=pd.DataFrame(Busca)
'''

'\nBusca=Numb(BEST)\nprint(pd.DataFrame(Busca))\ndf=pd.DataFrame(Busca)\n'

In [0]:
# print(df)


In [18]:
'''
Streams=4
Change=range(Streams+4) # Streams+4 so para ficar com um visual melhor
for k in range(Streams):
  plt.plot(Change,df.iloc[:,k])
plt.xlabel('Stages')
plt.ylabel('Temperature (K)')
'''

"\nStreams=4\nChange=range(Streams+4) # Streams+4 so para ficar com um visual melhor\nfor k in range(Streams):\n  plt.plot(Change,df.iloc[:,k])\nplt.xlabel('Stages')\nplt.ylabel('Temperature (K)')\n"

In [19]:
'''
print(tempInicial)
print(tempAlvo)
print(df)
'''

'\nprint(tempInicial)\nprint(tempAlvo)\nprint(df)\n'

In [20]:
Corrente=[]
When=[]
for i in range(100):
  x=np.zeros((NPAR,cols))
  for i in range(NPAR):
    for j in range(cols):
      r=np.random.random()
      x[i,j]=r*(MAX[j]-MIN[j])+MIN[j]
  Ind_I,Ind_J,deltaT, Split, WhenSplit, Alpha=SharkBuildMatriz(x)
  Corrente.append(Split)
  When.append(WhenSplit)
print(Corrente)
print(When)

[2, 2, 1, 1, 1, 0, 1, 0, 2, 3, 1, 1, 0, 2, 0, 3, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 1, 1, 1, 3, 2, 2, 2, 2, 1, 3, 3, 2, 2, 1, 1, 1, 1, 2, 1, 1, 3, 2, 0, 1, 2, 1, 1, 3, 0, 1, 2, 2, 2, 3, 1, 2, 1, 3, 1, 1, 0, 2, 2, 3, 2, 3, 1, 1, 1, 2, 3, 1, 1, 2, 0, 2, 1, 1, 1, 1, 2, 0, 2, 2, 0, 3, 2, 1, 1, 0, 3, 3, 3, 1]
[2, 4, 4, 1, 3, 0, 0, 0, 3, 2, 1, 1, 1, 2, 3, 2, 3, 2, 1, 0, 4, 4, 3, 0, 3, 3, 1, 1, 2, 3, 4, 2, 2, 2, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 0, 1, 1, 2, 1, 2, 4, 1, 4, 1, 1, 1, 2, 3, 2, 3, 3, 1, 3, 0, 4, 4, 0, 1, 2, 1, 0, 1, 1, 2, 0, 3, 0, 4, 2, 3, 3, 1, 3, 2, 4, 0, 4, 1, 0, 0, 2, 3, 3, 2, 1, 1, 3, 2, 1, 1]


In [21]:
print(Alpha)

0.9767810939481908
